// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANUTk4UxVTG8IzMieerRFGNXvbU94dd9w',
    appId: '1:680892252301:web:5f7ed2e82a9f07c49f22c4',
    messagingSenderId: '680892252301',
    projectId: 'shopapp-3b41f',
    authDomain: 'shopapp-3b41f.firebaseapp.com',
    databaseURL: 'https://shopapp-3b41f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shopapp-3b41f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCakeKE7zIGxdwMLhqj4Ge9QHV6B44CB8c',
    appId: '1:680892252301:android:769a1d324161143e9f22c4',
    messagingSenderId: '680892252301',
    projectId: 'shopapp-3b41f',
    databaseURL: 'https://shopapp-3b41f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shopapp-3b41f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsIeNkzM7RBzWLRsk-jJLb0mdGn-twR8k',
    appId: '1:680892252301:ios:019c5d3ba0c3488a9f22c4',
    messagingSenderId: '680892252301',
    projectId: 'shopapp-3b41f',
    databaseURL: 'https://shopapp-3b41f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shopapp-3b41f.appspot.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsIeNkzM7RBzWLRsk-jJLb0mdGn-twR8k',
    appId: '1:680892252301:ios:403ae9e2aeb9eae99f22c4',
    messagingSenderId: '680892252301',
    projectId: 'shopapp-3b41f',
    databaseURL: 'https://shopapp-3b41f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shopapp-3b41f.appspot.com',
    iosBundleId: 'com.example.shopApp.RunnerTests',
  );
}
